// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbc3educIQB35nYyony-i1g_n3U4T2ZvM',
    appId: '1:938186650443:web:0b1447ecba68db32',
    messagingSenderId: '938186650443',
    projectId: 'greek-771801',
    authDomain: 'greek-771801.firebaseapp.com',
    databaseURL: 'https://greek-771801.firebaseio.com',
    storageBucket: 'greek-771801.appspot.com',
    measurementId: 'G-J9B6MRQ8LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNrlxqQ5bAEBhxcBoo3V4Wx2YqGX7Zmsc',
    appId: '1:938186650443:android:4e0633252fd0080baaaece',
    messagingSenderId: '938186650443',
    projectId: 'greek-771801',
    databaseURL: 'https://greek-771801.firebaseio.com',
    storageBucket: 'greek-771801.appspot.com',
  );
}
